Warning: fs was declared with const; use let for reassignable variables.
// 此文件由 scripts/export_character_library.py 自动生成，请勿手动修改。
var CHARACTER_LIBRARY_DATA = {
  "source_file": "character_library.xlsx",
  "source_sheet": "character_library",
  "generated_at": "2026-09-11T15:55:07+08:00",
  "normalized_legacy_rows": 0,
  "characters": [
    {
      "character_id": "C001",
      "character_name": "神气猫",
      "group_id": "animal_ip",
      "character_group": "动物IP",
      "character_type": "喜剧主角/理性搭档",
      "personality_tags": "可爱、呆萌、有脾气、聪明、喜欢吃、善良",
      "comedy_function": "吐槽者、观察者、纠正错误、制造认知反差",
      "suitable_reversal": "误会反转、认知反转、对象错位",
      "strength": "判断能力较强、愿意帮助朋友",
      "weakness": "爱面子、怕老鼠、怕水、容易被倒霉狗连累",
      "common_actions": "分析、提醒、吐槽、尝试解决问题",
      "common_conflicts": "倒霉狗错误行为导致麻烦",
      "suitable_words": "look, know, help, eat, no",
      "avoid_behavior": "不要变成完全愚蠢角色",
      "relationship": "与倒霉狗关系最紧密的固定搭档",
      "prompt_instruction": "保持聪明但可爱的形象，通过吐槽制造笑点",
      "frontend_name": "神气猫",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C002",
      "character_name": "倒霉狗",
      "group_id": "animal_ip",
      "character_group": "动物IP",
      "character_type": "喜剧主角/麻烦制造者",
      "personality_tags": "可爱、呆萌、傻乎乎、认真、一根筋、喜欢吃、善良",
      "comedy_function": "制造错误、推动剧情、承担反转结果",
      "suitable_reversal": "动作反噬、误会反转、认真做错事、越帮越乱",
      "strength": "热心、行动力强、愿意帮助别人",
      "weakness": "容易误判、方法错误但非常认真",
      "common_actions": "主动尝试、寻找解决办法、做夸张行动",
      "common_conflicts": "帮助别人反而制造问题",
      "suitable_words": "run, help, find, look, eat",
      "avoid_behavior": "不要设计成恶意角色",
      "relationship": "与神气猫组成经典喜剧组合",
      "prompt_instruction": "强调认真执行错误方案产生反差",
      "frontend_name": "倒霉狗",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C003",
      "character_name": "小白熊",
      "group_id": "animal_ip",
      "character_group": "动物IP",
      "character_type": "高频配角",
      "personality_tags": "友善、平和、无明显强烈性格",
      "comedy_function": "作为事件对象、被误会对象、揭示真相",
      "suitable_reversal": "误会反转、隐藏信息反转",
      "strength": "容易成为故事中心事件来源",
      "weakness": "主动喜剧能力较弱",
      "common_actions": "正常生活、提供线索、揭示真相",
      "common_conflicts": "被神气猫和倒霉狗错误理解",
      "suitable_words": "eat, give, play",
      "avoid_behavior": "不要强行增加复杂性格",
      "relationship": "神气猫和倒霉狗朋友",
      "prompt_instruction": "适合作为反转目标角色",
      "frontend_name": "小白熊",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C004",
      "character_name": "小白兔",
      "group_id": "animal_ip",
      "character_group": "动物IP",
      "character_type": "辅助角色",
      "personality_tags": "可爱、活泼、弱小",
      "comedy_function": "制造对象错位、弱者反差",
      "suitable_reversal": "弱者反杀、误会反转",
      "strength": "容易获得儿童好感",
      "weakness": "冲突主动性较弱",
      "common_actions": "玩耍、回应主角",
      "common_conflicts": "被保护或产生意外结果",
      "suitable_words": "jump, play, run",
      "avoid_behavior": "避免强攻击性",
      "relationship": "动物朋友",
      "prompt_instruction": "突出可爱和视觉表现",
      "frontend_name": "小白兔",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C005",
      "character_name": "小黄鸡",
      "group_id": "animal_ip",
      "character_group": "动物IP",
      "character_type": "辅助角色",
      "personality_tags": "活泼、可爱、动作明显",
      "comedy_function": "制造混乱、视觉笑点",
      "suitable_reversal": "动作反噬、视觉喜剧",
      "strength": "动作表达强",
      "weakness": "角色深度较少",
      "common_actions": "跑动、叫喊、制造小事件",
      "common_conflicts": "引发混乱",
      "suitable_words": "run, jump, look",
      "avoid_behavior": "不要承担复杂主线",
      "relationship": "动物朋友",
      "prompt_instruction": "适合短篇视觉笑点",
      "frontend_name": "小黄鸡",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C006",
      "character_name": "欢乐爸",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "家庭喜剧主角",
      "personality_tags": "可爱、呆萌、吃货、勇敢、善良、容易出洋相",
      "comedy_function": "家庭喜剧、身份反差、行动笑点",
      "suitable_reversal": "身份反转、动作反噬、视觉反差",
      "strength": "勇敢、善良、有行动力",
      "weakness": "怕老鼠、怕打针、容易尴尬、怕欢乐妈",
      "common_actions": "吃东西、冒险、证明自己",
      "common_conflicts": "自信行为导致尴尬结果",
      "suitable_words": "eat, big, scared, help",
      "avoid_behavior": "不要失去家庭温暖感",
      "relationship": "欢乐一家人核心成员",
      "prompt_instruction": "适合温馨搞笑故事",
      "frontend_name": "欢乐爸",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C007",
      "character_name": "欢乐妈",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "家庭稳定角色",
      "personality_tags": "善良、漂亮、会做饭、有主见",
      "comedy_function": "管理者、纠正者、家庭冲突推动",
      "suitable_reversal": "家庭反转、认知反转",
      "strength": "照顾家庭、解决问题",
      "weakness": "容易被欢乐爸行为影响",
      "common_actions": "提醒、管理、做饭",
      "common_conflicts": "欢乐爸制造麻烦",
      "suitable_words": "cook, food, help",
      "avoid_behavior": "不要设计成冷漠角色",
      "relationship": "欢乐爸妻子",
      "prompt_instruction": "作为家庭秩序维护者",
      "frontend_name": "欢乐妈",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C008",
      "character_name": "欢欢哥哥",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "儿童主角",
      "personality_tags": "可爱、帅气、偶尔闯祸",
      "comedy_function": "儿童视角、成长故事",
      "suitable_reversal": "误会反转、成长反转",
      "strength": "容易成为第一人称角色",
      "weakness": "冲动、容易犯错",
      "common_actions": "探索、玩耍、尝试",
      "common_conflicts": "错误尝试产生结果",
      "suitable_words": "play, run, find",
      "avoid_behavior": "不要成人化",
      "relationship": "乐乐哥哥",
      "prompt_instruction": "适合儿童视角内容",
      "frontend_name": "欢欢",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C009",
      "character_name": "乐乐妹妹",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "儿童辅助角色",
      "personality_tags": "可爱、漂亮、懂事、妈妈帮手",
      "comedy_function": "辅助主角、形成对比",
      "suitable_reversal": "家庭喜剧、认知反转",
      "strength": "细心、合作",
      "weakness": "主动冲突能力较弱",
      "common_actions": "帮助、观察",
      "common_conflicts": "哥哥闯祸后的补救",
      "suitable_words": "help, look",
      "avoid_behavior": "不要成为说教角色",
      "relationship": "欢欢妹妹",
      "prompt_instruction": "适合温馨互动",
      "frontend_name": "乐乐",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C010",
      "character_name": "淘淘表哥",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "喜剧配角",
      "personality_tags": "调皮、恶作剧、闯祸、自作自受",
      "comedy_function": "制造恶作剧、承担反噬笑点",
      "suitable_reversal": "动作反噬、追逐反转",
      "strength": "制造冲突能力强",
      "weakness": "容易过度调皮",
      "common_actions": "捉弄别人、设计恶作剧",
      "common_conflicts": "恶作剧伤到自己",
      "suitable_words": "run, hide, trick",
      "avoid_behavior": "不要变成恶意角色",
      "relationship": "家庭亲戚",
      "prompt_instruction": "适合短篇笑点",
      "frontend_name": "淘淘表哥",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C011",
      "character_name": "爷爷",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "家庭喜剧配角",
      "personality_tags": "幽默、老顽童、光头、爱唱歌、爱吃大蒜",
      "comedy_function": "身份反差、老人喜剧",
      "suitable_reversal": "身份反转、视觉反差",
      "strength": "幽默、有记忆点",
      "weakness": "唱歌难听、行为夸张",
      "common_actions": "唱歌、吃东西、玩乐",
      "common_conflicts": "认真行为产生搞笑结果",
      "suitable_words": "sing, eat",
      "avoid_behavior": "不要刻画严肃老人",
      "relationship": "欢乐一家人长辈",
      "prompt_instruction": "突出老顽童反差",
      "frontend_name": "爷爷",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C012",
      "character_name": "美国姑父",
      "group_id": "support_character",
      "character_group": "新增IP",
      "character_type": "聪明角色",
      "personality_tags": "聪明、成熟",
      "comedy_function": "解决问题、智慧反差",
      "suitable_reversal": "认知反转",
      "strength": "思考能力强",
      "weakness": "喜剧属性较少",
      "common_actions": "分析、解释",
      "common_conflicts": "与普通角色形成能力差异",
      "suitable_words": "know, think",
      "avoid_behavior": "不要削弱聪明设定",
      "relationship": "海外家庭成员",
      "prompt_instruction": "适合高阶内容",
      "frontend_name": "美国姑父",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C013",
      "character_name": "美国表哥",
      "group_id": "support_character",
      "character_group": "新增IP",
      "character_type": "聪明儿童角色",
      "personality_tags": "聪明",
      "comedy_function": "智慧型儿童角色",
      "suitable_reversal": "认知反转",
      "strength": "解决问题",
      "weakness": "喜剧标签较少",
      "common_actions": "观察、分析",
      "common_conflicts": "与淘淘表哥形成对比",
      "suitable_words": "know, find",
      "avoid_behavior": "不要设计为万能角色",
      "relationship": "海外家庭成员",
      "prompt_instruction": "适合高阶内容",
      "frontend_name": "美国表哥",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C014",
      "character_name": "姑姑",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "欢乐一家人",
      "personality_tags": "家庭成员/辅助角色",
      "comedy_function": "家庭场景连接者、推动家庭事件",
      "suitable_reversal": "家庭喜剧、误会反转",
      "strength": "连接家庭成员和外部角色",
      "weakness": "目前无明显固定性格",
      "common_actions": "参与家庭活动、提供背景关系",
      "common_conflicts": "家庭成员互动",
      "suitable_words": "family, home, help",
      "avoid_behavior": "不要强行设计复杂性格",
      "relationship": "欢乐一家人的姑姑成员",
      "prompt_instruction": "作为家庭故事中的关系角色使用，后续可根据案例积累补充",
      "frontend_name": "姑姑",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C015",
      "character_name": "奶奶",
      "group_id": "happy_family",
      "character_group": "欢乐一家人",
      "character_type": "欢乐一家人",
      "personality_tags": "长辈角色、温和、懂健康知识、会做饭",
      "comedy_function": "生活喜剧、经验型角色",
      "suitable_reversal": "认知反转、生活误会",
      "strength": "做饭、健康知识",
      "weakness": "喜剧特征较少，需要通过事件塑造",
      "common_actions": "做饭、提醒、照顾家人",
      "common_conflicts": "家庭生活问题",
      "suitable_words": "food, cook, health",
      "avoid_behavior": "不要强行制造夸张行为",
      "relationship": "欢乐一家人的长辈成员",
      "prompt_instruction": "适合家庭温馨故事和生活场景",
      "frontend_name": "奶奶",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C016",
      "character_name": "小猪",
      "group_id": "support_character",
      "character_group": "辅助角色",
      "character_type": "辅助角色",
      "personality_tags": "弱者、可爱、容易被欺负",
      "comedy_function": "弱者反差、被保护对象",
      "suitable_reversal": "弱者反杀、动作反噬、追逐反转",
      "strength": "容易引起同情",
      "weakness": "力量弱、容易害怕",
      "common_actions": "逃跑、求助、意外反击",
      "common_conflicts": "被追赶、被误会",
      "suitable_words": "run, hide, help",
      "avoid_behavior": "不要设计成恶意角色",
      "relationship": "辅助动物角色",
      "prompt_instruction": "适合制造弱者反转",
      "frontend_name": "小猪",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C017",
      "character_name": "小鸭子",
      "group_id": "support_character",
      "character_group": "辅助角色",
      "character_type": "辅助角色",
      "personality_tags": "小、可爱、活泼、容易跟随",
      "comedy_function": "视觉笑点、队伍互动",
      "suitable_reversal": "规模反转、对象错位、追逐反转",
      "strength": "外形可爱，视觉识别强",
      "weakness": "冲突能力有限",
      "common_actions": "跟随、奔跑、制造小混乱",
      "common_conflicts": "误会、排队、追逐",
      "suitable_words": "walk, run, follow",
      "avoid_behavior": "不要承担复杂剧情",
      "relationship": "辅助动物角色",
      "prompt_instruction": "适合群体场景",
      "frontend_name": "小鸭子",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C018",
      "character_name": "大灰狼",
      "group_id": "support_character",
      "character_group": "辅助角色/反派角色",
      "character_type": "辅助角色/反派角色",
      "personality_tags": "反派、食肉动物、追逐者、自信",
      "comedy_function": "制造压力、追逐喜剧、反派失败",
      "suitable_reversal": "弱者反杀、追逐反转、动作反噬",
      "strength": "制造冲突能力强",
      "weakness": "容易被固定为坏角色",
      "common_actions": "追赶、威胁、计划",
      "common_conflicts": "追逐失败、被反制",
      "suitable_words": "run, catch, chase",
      "avoid_behavior": "不要设计真实恐怖形象",
      "relationship": "辅助反派角色",
      "prompt_instruction": "适合儿童喜剧中的失败反派",
      "frontend_name": "大灰狼",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C019",
      "character_name": "大象",
      "group_id": "support_character",
      "character_group": "辅助角色/规模角色",
      "character_type": "辅助角色/规模角色",
      "personality_tags": "巨大、善良、力量大",
      "comedy_function": "规模反差、视觉喜剧",
      "suitable_reversal": "规模反转、工具失控",
      "strength": "视觉冲击强",
      "weakness": "体型过大造成问题",
      "common_actions": "移动、碰撞、帮助",
      "common_conflicts": "空间限制、误会",
      "suitable_words": "big, help, move",
      "avoid_behavior": "不要只作为力量展示",
      "relationship": "辅助动物角色",
      "prompt_instruction": "适合制造巨大反差笑点",
      "frontend_name": "大象",
      "normalized_from_shifted_row": false
    },
    {
      "character_id": "C020",
      "character_name": "小松鼠",
      "group_id": "support_character",
      "character_group": "辅助角色",
      "character_type": "辅助角色",
      "personality_tags": "灵活、胆小、跑得快、爱收集",
      "comedy_function": "动作喜剧、追逐元素",
      "suitable_reversal": "追逐反转、工具失控、对象错位",
      "strength": "行动灵活",
      "weakness": "胆小容易逃跑",
      "common_actions": "奔跑、收集、躲藏",
      "common_conflicts": "寻找物品、被追逐",
      "suitable_words": "run, find, hide",
      "avoid_behavior": "不要承担主要反转",
      "relationship": "辅助动物角色",
      "prompt_instruction": "适合短篇视觉动作笑点",
      "frontend_name": "小松鼠",
      "normalized_from_shifted_row": false
    }
  ]
};
