// 此文件由 scripts/export_reversal_mechanisms.py 自动生成，请勿手动修改。
var REVERSAL_MECHANISM_LIBRARY = {
  "schema_version": "reversal-mechanism-library-v2",
  "source_file": "reversal_mechanism_library.xlsx",
  "source_sheet": "reversal_mechanisms",
  "generated_at": "2026-08-10T14:56:30+08:00",
  "categories": [
    {
      "name": "认知反转",
      "count": 6
    },
    {
      "name": "行为喜剧",
      "count": 7
    },
    {
      "name": "语言概念",
      "count": 4
    },
    {
      "name": "视觉喜剧",
      "count": 2
    }
  ],
  "reversal_families": [
    {
      "name": "结果型反转",
      "count": 5
    },
    {
      "name": "关系型反转",
      "count": 1
    },
    {
      "name": "认知型反转",
      "count": 8
    },
    {
      "name": "价值型反转",
      "count": 2
    },
    {
      "name": "协作型反转",
      "count": 1
    },
    {
      "name": "责任型反转",
      "count": 1
    },
    {
      "name": "目标型反转",
      "count": 1
    }
  ],
  "mechanisms": [
    {
      "mechanism_id": "R001",
      "mechanism_name": "身份反转",
      "category": "认知反转",
      "core_formula": "观众认为角色是什么→最后发现角色完全不同",
      "setup": "建立角色原本身份和能力预期",
      "twist": "揭示隐藏身份或真实能力",
      "child_reason": "儿童喜欢发现原来猜错了",
      "visual_expression": "角色突然展示隐藏能力、身份变化",
      "suitable_characters": "神气猫、倒霉狗、小白兔",
      "suitable_words": "big, strong, help, no",
      "difficulty": "低",
      "example": "看似弱小的小兔子最后帮助大家解决问题",
      "risk": "避免复杂身份设定",
      "prompt_instruction": "先建立错误期待，最后通过画面揭示真实身份",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "惊喜",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R002",
      "mechanism_name": "弱者反杀",
      "category": "认知反转",
      "core_formula": "弱小角色被低估→最后反过来帮助或击败强者",
      "setup": "让强者轻视弱者",
      "twist": "弱者利用特殊能力完成反转",
      "child_reason": "满足儿童对公平和胜利的期待",
      "visual_expression": "小动物突然发挥能力",
      "suitable_characters": "小白兔、小白熊",
      "suitable_words": "small, help, run",
      "difficulty": "低",
      "example": "小兔子看起来害怕狼，最后帮助大家",
      "risk": "不能变成暴力冲突",
      "prompt_instruction": "突出弱者的智慧或特殊能力，不靠力量",
      "reversal_family": "价值型反转",
      "reversal_drive": "价值重新定义推动",
      "emotional_release": "爽快",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R003",
      "mechanism_name": "对象错位",
      "category": "认知反转",
      "core_formula": "角色认为对象A→实际对象B",
      "setup": "给观众和角色制造错误判断",
      "twist": "最后揭示真实对象",
      "child_reason": "儿童喜欢发现误会",
      "visual_expression": "打开门发现不同东西、看错物体",
      "suitable_characters": "神气猫、倒霉狗",
      "suitable_words": "look, see, find",
      "difficulty": "低",
      "example": "倒霉狗以为发现密道，实际是下水道",
      "risk": "必须保证视觉可理解",
      "prompt_instruction": "重点设计角色为什么会误会",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "惊喜",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R004",
      "mechanism_name": "隐藏信息反转",
      "category": "认知反转",
      "core_formula": "角色不知道关键信息→观众或结尾揭示",
      "setup": "制造悬念和猜测",
      "twist": "补充隐藏信息改变理解",
      "child_reason": "儿童喜欢提前猜测",
      "visual_expression": "最后展示真实原因",
      "suitable_characters": "所有角色",
      "suitable_words": "look, know, find",
      "difficulty": "中",
      "example": "以为朋友生病，最后发现只是误会",
      "risk": "不能依赖复杂解释",
      "prompt_instruction": "保证隐藏信息可以通过画面表达",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "好奇",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R005",
      "mechanism_name": "误会反转",
      "category": "认知反转",
      "core_formula": "错误理解事件→真实原因完全不同",
      "setup": "连续增加错误线索",
      "twist": "最后公布简单真实原因",
      "child_reason": "误会升级释放笑点",
      "visual_expression": "表情夸张、错误判断",
      "suitable_characters": "神气猫、倒霉狗",
      "suitable_words": "bad, sick, red",
      "difficulty": "低",
      "example": "红色液体被认为是血，实际是果汁",
      "risk": "误会过程必须合理",
      "prompt_instruction": "增加线索升级，让角色越来越相信错误答案",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "爆笑",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R006",
      "mechanism_name": "动作反噬",
      "category": "行为喜剧",
      "core_formula": "角色行动解决问题→结果伤害自己或制造问题",
      "setup": "角色带着目标行动",
      "twist": "行动结果与目标相反",
      "child_reason": "喜欢看到意外结果",
      "visual_expression": "摔倒、混乱、尴尬",
      "suitable_characters": "倒霉狗、淘淘表哥",
      "suitable_words": "run, help, do",
      "difficulty": "低",
      "example": "想帮忙却让事情越来越乱",
      "risk": "避免真实伤害",
      "prompt_instruction": "动作必须推动剧情，不要无关搞笑",
      "reversal_family": "结果型反转",
      "reversal_drive": "行为导致",
      "emotional_release": "爆笑",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R007",
      "mechanism_name": "工具失控",
      "category": "行为喜剧",
      "core_formula": "工具帮助角色→工具造成更大问题",
      "setup": "角色使用新工具",
      "twist": "工具产生意外效果",
      "child_reason": "儿童喜欢失控场面",
      "visual_expression": "机器失灵、物品爆发",
      "suitable_characters": "倒霉狗、欢乐爸",
      "suitable_words": "big, use, make",
      "difficulty": "中",
      "example": "机器人帮忙结果制造混乱",
      "risk": "注意安全和可控性",
      "prompt_instruction": "强调工具结果反差",
      "reversal_family": "结果型反转",
      "reversal_drive": "对象变化推动",
      "emotional_release": "爆笑",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R008",
      "mechanism_name": "认真做错事",
      "category": "行为喜剧",
      "core_formula": "角色目标正确→方法极其错误→角色认真执行",
      "setup": "角色想帮助别人",
      "twist": "采用离谱方法",
      "child_reason": "认真和荒谬形成反差",
      "visual_expression": "认真表情配荒谬动作",
      "suitable_characters": "倒霉狗",
      "suitable_words": "help, find, do",
      "difficulty": "低",
      "example": "为了确认病情掏下水道",
      "risk": "不能只是愚蠢",
      "prompt_instruction": "角色必须相信自己做得对",
      "reversal_family": "结果型反转",
      "reversal_drive": "行为导致",
      "emotional_release": "爆笑",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R009",
      "mechanism_name": "越帮越乱",
      "category": "行为喜剧",
      "core_formula": "第一次解决失败→继续补救→问题扩大",
      "setup": "建立连续升级",
      "twist": "每次补救产生新问题",
      "child_reason": "适合长故事",
      "visual_expression": "混乱逐渐扩大",
      "suitable_characters": "倒霉狗、淘淘表哥",
      "suitable_words": "help, fix, try",
      "difficulty": "中",
      "example": "想帮助朋友却造成连续事故",
      "risk": "需要清晰因果",
      "prompt_instruction": "设计连续升级链条",
      "reversal_family": "结果型反转",
      "reversal_drive": "行为导致",
      "emotional_release": "爆笑",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R010",
      "mechanism_name": "追逐反转",
      "category": "行为喜剧",
      "core_formula": "追逐关系改变→追的人最后被追",
      "setup": "建立追逐目标",
      "twist": "身份位置交换",
      "child_reason": "动作节奏强",
      "visual_expression": "奔跑、躲藏、突然转向",
      "suitable_characters": "大灰狼、倒霉狗",
      "suitable_words": "run, catch",
      "difficulty": "低",
      "example": "狼追小动物最后自己逃跑",
      "risk": "避免危险感过强",
      "prompt_instruction": "突出搞笑追逐而不是恐怖",
      "reversal_family": "关系型反转",
      "reversal_drive": "关系推动",
      "emotional_release": "爽快",
      "similarity_risk": "low",
      "batch_usage_hint": "适合Top6组合补充"
    },
    {
      "mechanism_id": "R011",
      "mechanism_name": "字面化反转",
      "category": "语言概念",
      "core_formula": "词语普通理解→按照字面另一含义发生",
      "setup": "利用语言双关",
      "twist": "产生意外解释",
      "child_reason": "喜欢语言游戏",
      "visual_expression": "文字和画面冲突",
      "suitable_characters": "所有角色",
      "suitable_words": "open, fly, run",
      "difficulty": "中",
      "example": "角色理解错一个词产生误会",
      "risk": "低龄儿童需要画面辅助",
      "prompt_instruction": "优先选择简单英语词",
      "reversal_family": "认知型反转",
      "reversal_drive": "规则运行推动",
      "emotional_release": "惊喜",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R012",
      "mechanism_name": "偷换概念",
      "category": "语言概念",
      "core_formula": "同一句话前后含义改变",
      "setup": "建立语言期待",
      "twist": "最后改变解释",
      "child_reason": "产生突然笑点",
      "visual_expression": "对话反差",
      "suitable_characters": "神气猫、倒霉狗",
      "suitable_words": "no, good, look",
      "difficulty": "中",
      "example": "询问吃不吃最后变成不给",
      "risk": "不要依赖复杂语言",
      "prompt_instruction": "保持英文短句",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "爆笑",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R013",
      "mechanism_name": "一词多义",
      "category": "语言概念",
      "core_formula": "同一个词产生两个理解",
      "setup": "制造认知偏差",
      "twist": "切换词义",
      "child_reason": "语言惊喜",
      "visual_expression": "画面展示两个含义",
      "suitable_characters": "所有角色",
      "suitable_words": "open, fly, play",
      "difficulty": "中",
      "example": "同一个词在不同场景产生误会",
      "risk": "低词汇阶段谨慎使用",
      "prompt_instruction": "确保目标词真的自然出现",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "惊喜",
      "similarity_risk": "medium",
      "batch_usage_hint": "可常规使用"
    },
    {
      "mechanism_id": "R014",
      "mechanism_name": "认知差异",
      "category": "语言概念",
      "core_formula": "角色掌握信息不同→产生不同判断",
      "setup": "设置角色信息差",
      "twist": "揭示真实信息",
      "child_reason": "儿童喜欢知道秘密",
      "visual_expression": "角色表情和观众视角切换",
      "suitable_characters": "神气猫、倒霉狗",
      "suitable_words": "know, see, think",
      "difficulty": "低",
      "example": "角色相信错误事实，观众提前知道真相",
      "risk": "不要让信息过于隐蔽",
      "prompt_instruction": "利用观众比角色多知道一点制造期待",
      "reversal_family": "认知型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "好奇",
      "similarity_risk": "medium",
      "batch_usage_hint": "适合Top6组合补充"
    },
    {
      "mechanism_id": "R015",
      "mechanism_name": "夸张升级",
      "category": "视觉喜剧",
      "core_formula": "普通事情→越来越夸张",
      "setup": "建立正常尺度",
      "twist": "不断放大结果",
      "child_reason": "儿童喜欢巨大、新奇画面",
      "visual_expression": "巨大物体、大表情、大动作",
      "suitable_characters": "欢乐爸、倒霉狗",
      "suitable_words": "big, very",
      "difficulty": "低",
      "example": "小问题变成巨大混乱",
      "risk": "保持儿童友好",
      "prompt_instruction": "通过画面而不是解释表达夸张",
      "reversal_family": "结果型反转",
      "reversal_drive": "对象变化推动",
      "emotional_release": "爆笑",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R016",
      "mechanism_name": "规模反转",
      "category": "视觉喜剧",
      "core_formula": "大小力量关系与预期相反",
      "setup": "建立大小认知",
      "twist": "小变大或大变小",
      "child_reason": "直接视觉笑点",
      "visual_expression": "尺寸变化",
      "suitable_characters": "小白兔、大象",
      "suitable_words": "big, small",
      "difficulty": "低",
      "example": "小动物解决巨大问题",
      "risk": "避免复杂世界观",
      "prompt_instruction": "优先使用简单视觉变化",
      "reversal_family": "价值型反转",
      "reversal_drive": "价值重新定义推动",
      "emotional_release": "佩服",
      "similarity_risk": "high",
      "batch_usage_hint": "建议单批少量使用"
    },
    {
      "mechanism_id": "R017",
      "mechanism_name": "协作互补",
      "category": "行为喜剧",
      "core_formula": "单个角色各自受限→发现能力互补→分工共同完成",
      "setup": "建立双方各自擅长和受限之处",
      "twist": "两个不完整办法组合成只有合作才能完成的结果",
      "child_reason": "儿童喜欢看到不同能力拼在一起解决问题",
      "visual_expression": "两名角色交替动作，工具或位置互相补位",
      "suitable_characters": "所有角色",
      "suitable_words": "help, together, can",
      "difficulty": "中",
      "example": "一个够不到高处、一个搬不动物品，配合后完成任务",
      "risk": "避免简单喊朋友来帮忙，必须表现能力互补",
      "prompt_instruction": "先让两种单人办法因不同限制失败，再用分工产生新结果",
      "reversal_family": "协作型反转",
      "reversal_drive": "关系推动",
      "emotional_release": "佩服",
      "similarity_risk": "low",
      "batch_usage_hint": "适合Top6组合补充"
    },
    {
      "mechanism_id": "R018",
      "mechanism_name": "主动承担与修复",
      "category": "行为喜剧",
      "core_formula": "角色行动造成具体问题→主动承担并修复→修复改变状态或关系",
      "setup": "展示问题确由角色选择造成且能够修复",
      "twist": "角色不是因错误获奖，而是用修复行动形成新结果",
      "child_reason": "儿童能从可见因果理解承担和补救",
      "visual_expression": "角色停顿确认后果，主动回头整理、归位或修补，伙伴反应改变",
      "suitable_characters": "所有角色",
      "suitable_words": "sorry, fix, help",
      "difficulty": "中",
      "example": "角色弄乱路线标记后主动重新排列，让大家安全通过",
      "risk": "避免说教或让道歉替代真实修复",
      "prompt_instruction": "问题、承担和修复均须可见，反转来自修复结果",
      "reversal_family": "责任型反转",
      "reversal_drive": "行为导致",
      "emotional_release": "温暖",
      "similarity_risk": "low",
      "batch_usage_hint": "适合Top6组合补充"
    },
    {
      "mechanism_id": "R019",
      "mechanism_name": "目标转向",
      "category": "认知反转",
      "core_formula": "角色追逐表面目标→行动暴露新的具体目标→角色主动转向",
      "setup": "用可见线索建立原目标及被忽略的信息",
      "twist": "角色根据新证据改变行动目标，成功标准随之改变",
      "child_reason": "儿童喜欢发现大家原来追错了目标",
      "visual_expression": "原目标和新目标同框形成清楚方向变化",
      "suitable_characters": "所有角色",
      "suitable_words": "find, go, help",
      "difficulty": "中",
      "example": "角色追逐终点旗时发现旗子在标记迷路伙伴的位置，转而带伙伴回来",
      "risk": "不得靠结尾说教或突然新增任务完成转向",
      "prompt_instruction": "新目标必须由前置可见线索和角色主动选择产生",
      "reversal_family": "目标型反转",
      "reversal_drive": "信息差推动",
      "emotional_release": "惊喜",
      "similarity_risk": "medium",
      "batch_usage_hint": "适合Top6组合补充"
    }
  ]
};
